### ISSUE TITLE
Checking packages used

### ISSUE THREAD

**Issue by padpadpadpad** [dbarneche/nature20200508666#1]
Hi Diego

First thing I have checked is whether all the packages loaded have been used in any of the other R Scripts...

I haven't checked some of the ones that are key to knitting documents:
- drake
- rmarkdown
- bookdown
- tinytex
- knitr

Of the others, these are not present in any other R script.

```r
library(kableExtra) # not present in any other script
library(lubridate) # not present in any other script
library(gamm4) # not present in any other script
library(MuMIn) # not present in any other script
library(mgcv) # not present in any other script
```

Wondering whether these are used or could be dropped from the packages script.

**Comment by dbarneche** [comment]
Great catch @padpadpadpad, I'll drop them now!
