### ISSUE TITLE
Where does table output go?

### ISSUE THREAD

**Issue by padpadpadpad** [dbarneche/nature20200508666#2]
Currently the table output does not lead anywhere in output. So when anyone runs 

`drake::make(plan, targets = c("fig_1_pdf", "fig_2_pdf", "ed_table_2"), lock_envir = FALSE)` 

ed_table_2 does not have any output which to me was a bit confusing. Could we save out the .csv as output? Think that would (a) be very easy to do and (b) allow people to recreate the actual values in the table.

**Comment by dbarneche** [comment]
Great point, adding that now.
